FROM openjdk:11-jdk-slim

ARG DATABASE_HOST
ENV DATABASE_HOST ${DATABASE_HOST}
ARG DATABASE_USERNAME
ENV DATABASE_USERNAME ${DATABASE_USERNAME}
ARG DATABASE_PASSWORD
ENV DATABASE_PASSWORD ${DATABASE_PASSWORD}

WORKDIR /app

COPY . .

RUN ./gradlew bootJar

EXPOSE 8080

CMD ["java", "-jar", "build/libs/react-native-svg-icons-server.jar"]
